### ISSUE TITLE
Spotfy Connect

### ISSUE THREAD

**Issue by Monk007** [oyvindsam/SpotMute#7]
I am using an Android 7 tablet to control an Arcam RPlay (Play-Fi device with built-in Spotify) using Spotify Connect. I have enabled "devicd broadcast status"  in Spotify but it is greyed out  when the external device is connected. The ads are not muted although they appear to be counted by SpotMute. I don't know if this is an intentional limitation but would it be possible to consider supporting this in future?

**Comment by Monk007** [comment]
Apologies, I'd just like to add that the track titles are being detected as they show up in the notification message despite "device broadcast status" being greyed out when Spotify Connect is on. However, ads play at full volume.

**Comment by oyvindsam** [comment]
Yes, currently only the phone/tablet's media volume is muted, and it is a limitation with this basic implementation. It is probably very possible to mute a Spotify Connect device with the [Spotify SDK for Andorid](https://developer.spotify.com/documentation/android/), however I unfortunately have no plans to add it.
