### ISSUE TITLE
[Request] Android TV support

### ISSUE THREAD

**Issue by janowakps** [oyvindsam/SpotMute#8]
As in the title, it would be great if this application could also work on Android TV
![image](https://user-images.githubusercontent.com/36198623/117544993-2326f900-b024-11eb-8fa0-a70e18989093.png)

**Comment by oyvindsam** [comment]
Hi this does not work, afaik Spotify for ATV is just a wrapper for chromecast, and muting the phone will not affect the tv, nor is there an api to mute a chromecast device. A better error message could probably be helpful though

**Comment by oyvindsam** [comment]
Yeah my bad, I don't have ATV so just quickly checked it out. Anyway the atv app is even simpler than Spotify lite, with no device broadcast feature, so won't work for the same reason :/
